#!/usr/bin/env python2.7

import sys
from glob import glob
import os
from os.path import basename
import shutil
import argparse
from argparse import ArgumentDefaultsHelpFormatter as help_formatter


def get_column_output(s, ncols=3):
    """Format input list of strings s into ncols columns."""

    s = [ s[i:i+ncols] for i in range(0, len(s), ncols) ]
    col_width = 2 + max(len(word) for row in s for word in row)

    s_formatted = "" 
    for row in s:
        s_formatted += "\t" + "".join(word.ljust(col_width) for word in row) + "\n"

    return s_formatted 


def remove_except(files=None, force=False,
                  recursive=False):
    """Delete all files/directories except the ones specified.
       
       # TODO: multiple files to ignore

        Parameters:
        -----------
            files: list of strings
                Delete all files/directories except the ones specified.
            force: bool
                Remove files without asking.
            recursive: bool
                Whether to recursively remove eventual directories.
    """

    # exit if no arguments are supplied
    if not files:
        sys.exit("Error: no arguments supplied")

    # add calling script to files which should be left untouched
    files = list(files)
    script = basename(sys.argv[0])
    if os.path.isfile(script):
        args.append(script)

    # ignore per default
    #if os.path.isfile(ignore):
    #    args.append(ignore)

    # fill list of files to be deleted
    del_list = []
    all_files = sorted(glob("*"))
    
    for file in all_files:
        if file not in files:
            del_list.append(file)

    # output in columns and removal confirmation
    if not force:
        print "Current directory listing:"
        print
        print get_column_output(all_files) 
        print "Remove all files except"
        print
        print get_column_output(files)
        print "?"
        print
        input = raw_input("Press (Yes | Y | yes | y) to delete files:\n")
        print
    else:
        input = 'Y'

    if input in ('Yes', 'Y', 'yes', 'y'):
        for i in del_list:
            try:
                os.remove(i)
            except OSError:
                if recursive:
                    shutil.rmtree(i) 
                    if not force:
                        print "deleting", basename(i)
            else:
                if not force:
                    print "deleting", basename(i)
    else:
        print "Aborting removal. \n"


if __name__ == '__main__':

    parser = argparse.ArgumentParser(formatter_class=help_formatter)
    parser.add_argument("files", nargs="+",
                        help="Delete all files/directories except the ones specified.")
    parser.add_argument("-f", "--force", action="store_true",
                        help="Remove files without asking.")
    parser.add_argument("-r", "--recursive", action="store_true",
                        help="Whether to recursively remove eventual directories.")
    #parser.add_argument("-i", "--ignore", nargs="*", default=["EP_SETTINGS.cfg", "input.xml"], 
    #                    help="Files/Folders to ignore per default.")
    args = parser.parse_args()

    remove_except(files=args.files, force=args.force, 
                  recursive=args.recursive)

