#!/usr/bin/env python2.7

import os
import shutil
import argh
import sys
from glob import glob


def get_column_output(s, ncols=10):
    """Format input list of strings into ncols columns."""

    s = [ s[i:i+ncols] for i in range(0, len(s), ncols) ]
    col_width = 2 + max(len(word) for row in s for word in row)

    s_formatted = "" 
    for row in s:
        s_formatted += "".join(word.ljust(col_width) for word in row) + "\n"

    return s_formatted 


@argh.arg_hack()
def remove_except(force=False,
                  recursive=False, *args):
    """Delete all files/directories except the ones specified in *args.

        Parameters:
        -----------
            force: bool
                Remove files without asking if set True.
            recursive: bool
                Whether to recursively remove eventual directories.
    """

    # if no arguments are supplied, exit
    if not args:
        sys.exit("Error: no arguments supplied. Aborting.")

    # add calling script to files which should be left untouched
    args = list(args)
    args.append(sys.argv[0])

    # fill list of files to be deleted
    del_list = []
    
    for file in glob("*"):
        if file not in args:
            del_list.append(file)
        del_list.sort()

    # output in columns 
    print get_column_output(del_list) 
    print
    print "Remove all files except"
    print
    print get_column_output(args)
    print
    print "?"
    print

    # get removal confirmation
    if not force:
        input = raw_input("Press (Yes | Y | yes | y) to delete files:\n")
    else:
        input = 'Y'

    if input in ('Yes', 'Y', 'yes', 'y'):
        for i in del_list:
            print "deleting", i
            try:
                pass
                # os.remove(i)
            except OSError:
                pass
                # shutil.rmtree(i) 


if __name__ == '__main__':
    argh.dispatch_command(remove_except)

